# fly.toml app configuration file generated for klipin on 2026-04-08T23:05:38+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'klipin'
primary_region = 'sin'

[build]
  [build.args]
    NEXT_PUBLIC_SUPABASE_URL = "https://aiohmmgyekvfzixjetar.supabase.co"
    NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpb2htbWd5ZWt2ZnppeGpldGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2MDQ1MTUsImV4cCI6MjA5MTE4MDUxNX0.t97-tuoITNCiRlVT5C-F4U2HvArcXcqbQZCA18qofBQ"
    NEXT_PUBLIC_APP_URL = "https://klipin.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
